function [emptyGlomeruliInfoElement]=                               GetGlomeruliInfoElement
    % includes all previously used fields used to maintain compatibility with matfiles generated using old code.
emptyGlomeruliInfoElement=struct(        ...
    'names',                    [], ...
    'status',                    [], ...
   'deltaF',                   [], ...
    'peak',                     [], ...
    'peakIndx',                 [], ...
     'meanBackGround',           [], ...
    'baseToPeak',               [], ...
    'originalGlomeruli',        [], ...
    'sliceNumberOfResponseOnset', [],...
    'approxMaxIndx',            [],...
    'cycleNum',                 [], ...
    'originalMeanBackGround',   [], ...
   'heatMap',                   [], ...
    'heatMapMasked',            [], ...
    'silentGloms',              [], ...
    'glomeruliToKeep',          [], ...
    'glomeruliToBeAnalysed',    [], ...
    'plot',                     [], ...
    'timeVec',                  [], ...
    'userBase1',                [], ...
    'userBase2',                [], ...
    'userDefinedPeak',          [], ...
    'base1Slices',              [], ...
    'base2Slices',              [], ...
    'coOrdinates',              [], ...
    'originalCoOrdinates',      [], ...
    'baseLine',                 [], ...
    'baseLine2',                [], ...
    'deltaFwithBackGround',     [], ...
    'displayPic',               [], ...
    'previousLsmInfo',          [], ...
    'lsmDescriptors',           [],...
    'decodedGroup',             [],...
    'dissecter',                [],...
    'riseTime',                 [],...
    'baselinePlot',             [],...
    'meanBaselineValue',           [],...
    'baselineStatus',           [],...
    'fullLength',               [],...
    'croppedPlot',              [],...
    'tCroppedPlot',             [],...
    'extrapolated',             [],...
    'negativeCurveArea',        [],...
    'binningLabel',             [],...
    'binnedArea',               [],...
    'dfPeak',                   [],... %obsolete
    'peakOfInterpedCurve',       [],...
    'dfPeakIndx',               [],... %obsolete
    'peakIndxOfInterpedCurve',   [],...
    'timeToPeak',               [],...
    'timeTo90',                 [],...
    'timeTo66',                 [],...
    'timeTo33',                 [],...
    'falltime',                 []);
end
