function [lsmDescriptors]=                                          InitialiseLsmDescriptors()
lsmDescriptors= struct(...
    'timeInterval'                      ,[],...
    'sliceNumber'                       ,[],...
    'originalLength'                    ,[],...
    'path'                              ,[],...
    'lsmFileName'                       ,[],...
    'meanOfSlices'                      ,[],...
    'approxMax'                         ,[],...
    'approxMaxIndx'                     ,[],...    
    'previousLsmInfo'                     ,[],...
    'slicesTakenAfterPeak'              ,[],...
    'slicesCroppedFromStart'            ,[],...
    'originalMaxIndx'                   ,[],...
    'originalSlicesCroppedFromStart'    ,[]);
    lsmDescriptors.comments={''};
    
end